const ProductList = [
    {
        id: 1,
        name: "Samsung S21 FE 5G",
        price: 33999,
        url1: "./Assets/samsung.png",
        url2:"https://m.media-amazon.com/images/I/817wzcDRQAL._SX679_.jpg",
        colors: ['Olive', 'Graphite', "Lavendar", 'White'],
        features: {
            ram:"6",
            memory:"128",
            processor: "MediaTek Dimensity 1200 Processor",
            os: "Android 12.0",
            screensize: "6.4",
            display: "AMOLED",
            battery: 4500,
            weight: 177,
            warranty: 6,
        }
    },
    {
        id: 2,
        name: "Vivo X70 Pro",
        price: 40599,
        url1: "./Assets/vivo.png",
        url2:"https://m.media-amazon.com/images/I/21q4I7ziVqL.jpg",
        colors: ['Aurora Dawn', 'Cosmic Black'],
        features: {
            ram:"6",
            memory:"128",
            processor: "MediaTek Dimensity 1200 Processor",
            os: "Android 12.0",
            screensize: "6.56",
            display: "Full HD+",
            battery: 4450,
            weight: 610,
            warranty: 6,
        }
    },
    {
        id: 3,
        name: "Poco F4",
        price: 22999,
        url1: "./Assets/poco.png",
        url2:"https://rukminim1.flixcart.com/image/832/832/l4n2oi80/mobile/h/h/i/-original-imagfhuecztmg3gz.jpeg?q=70",
        colors: ['Olive', 'Graphite', "Lavendar", 'White'],
        features: {
            ram:"6",
            memory:"128",
            processor: "MediaTek Dimensity 1200 Processor",
            os: "Android 12.0",
            screensize: "6.4",
            display: "AMOLED",
            battery: 4500,
            weight: 177,
            warranty: 6,
        }
    },
    {
        id: 4,
        name: "Realme 9",
        price: 20999,
        url1: "./Assets/realme.png",
        url2:"https://rukminim1.flixcart.com/image/832/832/l3t2fm80/mobile/6/w/7/-original-imageu8cuhfumfw7.jpeg?q=70",
        colors: ['Olive', 'Graphite', "Lavendar", 'White'],
        features: {
            ram:"6",
            memory:"128",
            processor: "MediaTek Dimensity 1200 Processor",
            os: "Android 12.0",
            screensize: "6.4",
            display: "AMOLED",
            battery: 4500,
            weight: 177,
            warranty: 6,
        }
    },
    {
        id: 5,
        name: "Oppo K10 5G",
        price: 16499,
        url1: "./Assets/oppo.png",
        url2:"https://rukminim1.flixcart.com/image/312/312/l4d2ljk0/mobile/x/d/z/-original-imagf9wt5emzsjqz.jpeg?q=70",
        colors: ['Olive', 'Graphite', "Lavendar", 'White'],
        features: {
            ram:"6",
            memory:"128",
            processor: "MediaTek Dimensity 1200 Processor",
            os: "Android 12.0",
            screensize: "6.4",
            display: "AMOLED",
            battery: 4500,
            weight: 177,
            warranty: 6,
        }
    },
    {
        id: 6,
        name: "Motorola edge 30",
        price: 22249,
        url1: "./Assets/moto.png",
        url2:"https://rukminim1.flixcart.com/image/312/312/l2xmqvk0/mobile/3/k/f/-original-image674nvdc4aws.jpeg?q=70",
        colors: ['Olive', 'Graphite', "Lavendar", 'White'],
        features: {
            ram:"6",
            memory:"128",
            processor: "MediaTek Dimensity 1200 Processor",
            os: "Android 12.0",
            screensize: "6.4",
            display: "AMOLED",
            battery: 4500,
            weight: 177,
            warranty: 6,
        }
    }, 
    {
        id: 7,
        name: "Samsung S21 FE 5G",
        price: 33999,
        url1: "./Assets/samsung.png",
        url2:"https://m.media-amazon.com/images/I/817wzcDRQAL._SX679_.jpg",
        colors: ['Olive', 'Graphite', "Lavendar", 'White'],
        features: {
            ram:"6",
            memory:"128",
            processor: "MediaTek Dimensity 1200 Processor",
            os: "Android 12.0",
            screensize: "6.4",
            display: "AMOLED",
            battery: 4500,
            weight: 177,
            warranty: 6,
        }
    },
    {
        id: 8,
        name: "Vivo X70 Pro",
        price: 40599,
        url1: "./Assets/vivo.png",
        url2:"https://m.media-amazon.com/images/I/21q4I7ziVqL.jpg",
        colors: ['Aurora Dawn', 'Cosmic Black'],
        features: {
            ram:"6",
            memory:"128",
            processor: "MediaTek Dimensity 1200 Processor",
            os: "Android 12.0",
            screensize: "6.56",
            display: "Full HD+",
            battery: 4450,
            weight: 610,
            warranty: 6,
        }
    },
    {
        id: 9,
        name: "Poco F4",
        price: 22999,
        url1: "./Assets/poco.png",
        url2:"https://rukminim1.flixcart.com/image/832/832/l4n2oi80/mobile/h/h/i/-original-imagfhuecztmg3gz.jpeg?q=70",
        colors: ['Olive', 'Graphite', "Lavendar", 'White'],
        features: {
            ram:"6",
            memory:"128",
            processor: "MediaTek Dimensity 1200 Processor",
            os: "Android 12.0",
            screensize: "6.4",
            display: "AMOLED",
            battery: 4500,
            weight: 177,
            warranty: 6,
        }
    },
    {
        id: 10,
        name: "Realme 9",
        price: 20999,
        url1: "./Assets/realme.png",
        url2:"https://rukminim1.flixcart.com/image/832/832/l3t2fm80/mobile/6/w/7/-original-imageu8cuhfumfw7.jpeg?q=70",
        colors: ['Olive', 'Graphite', "Lavendar", 'White'],
        features: {
            ram:"6",
            memory:"128",
            processor: "MediaTek Dimensity 1200 Processor",
            os: "Android 12.0",
            screensize: "6.4",
            display: "AMOLED",
            battery: 4500,
            weight: 177,
            warranty: 6,
        }
    },
    {
        id: 11,
        name: "Oppo K10 5G",
        price: 16499,
        url1: "./Assets/oppo.png",
        url2:"https://rukminim1.flixcart.com/image/312/312/l4d2ljk0/mobile/x/d/z/-original-imagf9wt5emzsjqz.jpeg?q=70",
        colors: ['Olive', 'Graphite', "Lavendar", 'White'],
        features: {
            ram:"6",
            memory:"128",
            processor: "MediaTek Dimensity 1200 Processor",
            os: "Android 12.0",
            screensize: "6.4",
            display: "AMOLED",
            battery: 4500,
            weight: 177,
            warranty: 6,
        }
    },
    {
        id: 12,
        name: "Motorola edge 30",
        price: 22249,
        url1: "./Assets/moto.png",
        url2:"https://rukminim1.flixcart.com/image/312/312/l2xmqvk0/mobile/3/k/f/-original-image674nvdc4aws.jpeg?q=70",
        colors: ['Olive', 'Graphite', "Lavendar", 'White'],
        features: {
            ram:"6",
            memory:"128",
            processor: "MediaTek Dimensity 1200 Processor",
            os: "Android 12.0",
            screensize: "6.4",
            display: "AMOLED",
            battery: 4500,
            weight: 177,
            warranty: 6,
        }
    },  {
        id: 13,
        name: "Samsung S21 FE 5G",
        price: 33999,
        url1: "./Assets/samsung.png",
        url2:"https://m.media-amazon.com/images/I/817wzcDRQAL._SX679_.jpg",
        colors: ['Olive', 'Graphite', "Lavendar", 'White'],
        features: {
            ram:"6",
            memory:"128",
            processor: "MediaTek Dimensity 1200 Processor",
            os: "Android 12.0",
            screensize: "6.4",
            display: "AMOLED",
            battery: 4500,
            weight: 177,
            warranty: 6,
        }
    },
    {
        id: 14,
        name: "Vivo X70 Pro",
        price: 40599,
        url1: "./Assets/vivo.png",
        url2:"https://m.media-amazon.com/images/I/21q4I7ziVqL.jpg",
        colors: ['Aurora Dawn', 'Cosmic Black'],
        features: {
            ram:"6",
            memory:"128",
            processor: "MediaTek Dimensity 1200 Processor",
            os: "Android 12.0",
            screensize: "6.56",
            display: "Full HD+",
            battery: 4450,
            weight: 610,
            warranty: 6,
        }
    },
    {
        id: 15,
        name: "Poco F4",
        price: 22999,
        url1: "./Assets/poco.png",
        url2:"https://rukminim1.flixcart.com/image/832/832/l4n2oi80/mobile/h/h/i/-original-imagfhuecztmg3gz.jpeg?q=70",
        colors: ['Olive', 'Graphite', "Lavendar", 'White'],
        features: {
            ram:"6",
            memory:"128",
            processor: "MediaTek Dimensity 1200 Processor",
            os: "Android 12.0",
            screensize: "6.4",
            display: "AMOLED",
            battery: 4500,
            weight: 177,
            warranty: 6,
        }
    },
    {
        id: 16,
        name: "Realme 9",
        price: 20999,
        url1: "./Assets/realme.png",
        url2:"https://rukminim1.flixcart.com/image/832/832/l3t2fm80/mobile/6/w/7/-original-imageu8cuhfumfw7.jpeg?q=70",
        colors: ['Olive', 'Graphite', "Lavendar", 'White'],
        features: {
            ram:"6",
            memory:"128",
            processor: "MediaTek Dimensity 1200 Processor",
            os: "Android 12.0",
            screensize: "6.4",
            display: "AMOLED",
            battery: 4500,
            weight: 177,
            warranty: 6,
        }
    },
    {
        id: 17,
        name: "Oppo K10 5G",
        price: 16499,
        url1: "./Assets/oppo.png",
        url2:"https://rukminim1.flixcart.com/image/312/312/l4d2ljk0/mobile/x/d/z/-original-imagf9wt5emzsjqz.jpeg?q=70",
        colors: ['Olive', 'Graphite', "Lavendar", 'White'],
        features: {
            ram:"6",
            memory:"128",
            processor: "MediaTek Dimensity 1200 Processor",
            os: "Android 12.0",
            screensize: "6.4",
            display: "AMOLED",
            battery: 4500,
            weight: 177,
            warranty: 6,
        }
    },
    {
        id: 18,
        name: "Motorola edge 30",
        price: 22249,
        url1: "./Assets/moto.png",
        url2:"https://rukminim1.flixcart.com/image/312/312/l2xmqvk0/mobile/3/k/f/-original-image674nvdc4aws.jpeg?q=70",
        colors: ['Olive', 'Graphite', "Lavendar", 'White'],
        features: {
            ram:"6",
            memory:"128",
            processor: "MediaTek Dimensity 1200 Processor",
            os: "Android 12.0",
            screensize: "6.4",
            display: "AMOLED",
            battery: 4500,
            weight: 177,
            warranty: 6,
        }
    },  {
        id: 19,
        name: "Samsung S21 FE 5G",
        price: 33999,
        url1: "./Assets/samsung.png",
        url2:"https://m.media-amazon.com/images/I/817wzcDRQAL._SX679_.jpg",
        colors: ['Olive', 'Graphite', "Lavendar", 'White'],
        features: {
            ram:"6",
            memory:"128",
            processor: "MediaTek Dimensity 1200 Processor",
            os: "Android 12.0",
            screensize: "6.4",
            display: "AMOLED",
            battery: 4500,
            weight: 177,
            warranty: 6,
        }
    },
    {
        id: 20,
        name: "Vivo X70 Pro",
        price: 40599,
        url1: "./Assets/vivo.png",
        url2:"https://m.media-amazon.com/images/I/21q4I7ziVqL.jpg",
        colors: ['Aurora Dawn', 'Cosmic Black'],
        features: {
            ram:"6",
            memory:"128",
            processor: "MediaTek Dimensity 1200 Processor",
            os: "Android 12.0",
            screensize: "6.56",
            display: "Full HD+",
            battery: 4450,
            weight: 610,
            warranty: 6,
        }
    },
    {
        id: 21,
        name: "Poco F4",
        price: 22999,
        url1: "./Assets/poco.png",
        url2:"https://rukminim1.flixcart.com/image/832/832/l4n2oi80/mobile/h/h/i/-original-imagfhuecztmg3gz.jpeg?q=70",
        colors: ['Olive', 'Graphite', "Lavendar", 'White'],
        features: {
            ram:"6",
            memory:"128",
            processor: "MediaTek Dimensity 1200 Processor",
            os: "Android 12.0",
            screensize: "6.4",
            display: "AMOLED",
            battery: 4500,
            weight: 177,
            warranty: 6,
        }
    },
    {
        id: 22,
        name: "Realme 9",
        price: 20999,
        url1: "./Assets/realme.png",
        url2:"https://rukminim1.flixcart.com/image/832/832/l3t2fm80/mobile/6/w/7/-original-imageu8cuhfumfw7.jpeg?q=70",
        colors: ['Olive', 'Graphite', "Lavendar", 'White'],
        features: {
            ram:"6",
            memory:"128",
            processor: "MediaTek Dimensity 1200 Processor",
            os: "Android 12.0",
            screensize: "6.4",
            display: "AMOLED",
            battery: 4500,
            weight: 177,
            warranty: 6,
        }
    },
    {
        id: 23,
        name: "Oppo K10 5G",
        price: 16499,
        url1: "./Assets/oppo.png",
        url2:"https://rukminim1.flixcart.com/image/312/312/l4d2ljk0/mobile/x/d/z/-original-imagf9wt5emzsjqz.jpeg?q=70",
        colors: ['Olive', 'Graphite', "Lavendar", 'White'],
        features: {
            ram:"6",
            memory:"128",
            processor: "MediaTek Dimensity 1200 Processor",
            os: "Android 12.0",
            screensize: "6.4",
            display: "AMOLED",
            battery: 4500,
            weight: 177,
            warranty: 6,
        }
    },
    {
        id: 24,
        name: "Motorola edge 30",
        price: 22249,
        url1: "./Assets/moto.png",
        url2:"https://rukminim1.flixcart.com/image/312/312/l2xmqvk0/mobile/3/k/f/-original-image674nvdc4aws.jpeg?q=70",
        colors: ['Olive', 'Graphite', "Lavendar", 'White'],
        features: {
            ram:"6",
            memory:"128",
            processor: "MediaTek Dimensity 1200 Processor",
            os: "Android 12.0",
            screensize: "6.4",
            display: "AMOLED",
            battery: 4500,
            weight: 177,
            warranty: 6,
        }
    }, 
]
module.exports = { ProductList }